version: "3.9"

services:
  web:
    build: .
    image: shoxakong/django-image:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - static_volume:/app/static
    entrypoint: ["/app/entrypoint.sh"]

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "8000:8000"
    depends_on:
      - web
    volumes:
      - ./nginx/sites-available/crm.conf:/etc/nginx/conf.d/crm.conf
      - static_volume:/static

volumes:
  static_volume:
