name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: djangoproject
          POSTGRES_USER: admin_user
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: djangoproject
      DB_USER: admin_user
      DB_PASSWORD: 1234
      DB_HOST: postgres
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for Postgres..."
          while ! pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
            sleep 1
          done
          echo "Postgres is ready!"

      - name: Run Migrations
        run: python manage.py migrate

